name: Package-all

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run Cargo Check
        run: cargo check

      - name: Run Tests
        run: cargo test

      - name: Build Release Binary
        run: cargo build --release

      - name: Package Binary
        run: |
          mkdir -p dist
          cp -r target/release/* dist/
          zip -r linux-package.zip dist/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: linux-package.zip
          retention-days: 2

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Run Cargo Check
        run: cargo check

      - name: Run Tests
        run: cargo test

      - name: Build Release Binary
        run: cargo build --release

      - name: Package Binary
        run: |
          mkdir dist
          copy target\release\* dist\
          powershell Compress-Archive -Path dist\* -DestinationPath windows-package.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: windows-package.zip
          retention-days: 2
